version: '3.4'
services:
  api:
    image: 75ca511593997bd1c011b6dbe8c6f50454e50333c6b446e39fc114df7708a5f9
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
